### ISSUE TITLE
Database schema

### ISSUE THREAD

**Issue by linakherchi** [codybreene/merkle_money#1]
- [x] Contains correct datatypes 
- [x] Contains appropriate constraints/details
    - [x] primary key
    - [x] not null 
    - [x] unique
    - [x] indexed
    - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
    - [x] foreign key and table name are lowercased, snake_cased and back_ticked
- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] the table's name are lowercased, snake_cased and back_ticked
    - [x] the table header column names are bolded
    - [x] columns names are lowercased and snaked_cased and back_ticked

**Comment by linakherchi** [comment]
Great job, Cody !

Two clarifications I am asking for: 

1) What is the goal of having an index on currency inside the wallets table. I know these will not hurt, but I am just curious
2) What is the price_date column inside the prices table? 

Thanks,

**Comment by codybreene** [comment]
Thanks, Lina! 

1. I thought it might make sense to have an index on the currency if we wanted to look up the wallets by currency, but I'm only anticipating maybe 10-15 currencies so maybe this isn't necessary. 

2. The price_date column refers to the date for which we're reporting prices -- i.e. on each day we'll have a high, low, open and close price for each currency. Maybe I don't need to store price data in the DB though, because there are quite a few public APIs I can pull from.

**Comment by linakherchi** [comment]
1. You can definitely keep the index on the currency. 
2. I do not think you need the prices table at all if you are going to use API calls. These will retrieve all the necessary information regarding currency prices.

**Comment by codybreene** [comment]
Do you think I need the cryptocurrencies table, if I'm going to be using a 3rd party API?

**Comment by linakherchi** [comment]
I think you still need the cryptocurrencies table. The number of columns inside your cryptocurrencies table will not be as big as the ones regarding prices, so keeping the cryptocurrencies table will be OK.

**Comment by codybreene** [comment]
Made the relevant edits -- this should be good to go!
